---
- name: configure postgresql
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"

- name: configure pg_hba
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"

- name: configure etcd
  template:
    src: etcd.j2
    dest: /etc/default/etcd
  when: "inventory_hostname == groups['postgresql'][0]"
  notify:
    - restart etcd

- meta: flush_handlers

- name: generate locale
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: export locale env
  become: yes
  lineinfile:
    dest: /etc/environment
    line: LC_ALL="en_US.UTF-8"

- name: create data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: soi
    group: soi
    mode: 0700
    recurse: yes
  changed_when: false

- name: locate patroni
  find:
    paths: /
    patterns: "patroni"
    recurse: yes
  register: location

- name: set location var
  set_fact:
    patroni_location: "{{ location.files[0].path }}"

- name: configure patroni
  template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
    owner: root
    group: root
    mode: 0644

- name: copy patroni systemd service file
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: 0644
  notify:

-  name: trigger patroni restart
   command: /bin/true
   notify: start postgres cluster

- meta: flush_handlers
